# Generated by Django 3.0.2 on 2021-11-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_list_m',
            name='Alter_ID',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='song_list_m',
            name='DM_ID',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='song_list_m',
            name='SC_ID',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='song_list_m',
            name='Time',
            field=models.FloatField(blank=True),
        ),
    ]
