# Generated by Django 3.0.2 on 2021-11-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20211119_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_list_m',
            name='Time',
            field=models.FloatField(default=0.0),
        ),
    ]
