# Generated by Django 3.0.2 on 2021-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_song_list_m_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_list_m',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
