# Generated by Django 3.0.2 on 2021-11-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_auto_20211122_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_list_m',
            name='default_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='categories_m',
            name='Category',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='new Category'),
        ),
        migrations.AlterField(
            model_name='song_list_m',
            name='Alter_ID',
            field=models.CharField(blank=True, max_length=30, verbose_name='Alternate Youtube ID'),
        ),
        migrations.AlterField(
            model_name='song_list_m',
            name='DM_ID',
            field=models.CharField(blank=True, max_length=30, verbose_name='DailyMotion ID'),
        ),
        migrations.AlterField(
            model_name='song_list_m',
            name='ID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Youtube ID'),
        ),
        migrations.AlterField(
            model_name='song_list_m',
            name='SC_ID',
            field=models.CharField(blank=True, max_length=30, verbose_name='SoundCloud ID'),
        ),
    ]
