# Generated by Django 3.0.2 on 2021-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_auto_20211125_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_list_m',
            name='SC_ID',
            field=models.CharField(blank=True, max_length=100, verbose_name='SoundCloud ID'),
        ),
    ]
