# Generated by Django 3.0.2 on 2021-11-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0007_auto_20211125_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_list_m',
            name='Title',
            field=models.CharField(max_length=50),
        ),
    ]
